spring:
  application:
    name: ghibli-lib

web:
  cors:
    allowed-origins: "http://localhost:5173"
    allowed-methods: GET, POST, PUT, DELETE
    allowed-headers: "Content-Type"
    exposed-headers: "Content-Encoding"